### ISSUE TITLE
wifi crashed

### ISSUE THREAD

**Issue by kongqi404** [Rohail33/Realking_kernel_sm8250#13]
I built the kernel using the latest commit and when I powered it on, the wifi module crashed.

**Comment by Rohail33** [comment]
> I built the kernel using the latest commit and when I powered it on, the wifi module crashed.

There's been a force push done... Reclone the repo and everything should be fine.

**Comment by kongqi404** [comment]
OK, i will try it.

Rohail33 ***@***.***> 于 2024年2月7日周三 16:29写道：
