### ISSUE TITLE
complie error “../drivers/ksu/Makefile: No such file or directory”

### ISSUE THREAD

**Issue by kongqi404** [Rohail33/Realking_kernel_sm8250#14]
I get a compilation error when I execute `build_kernel.sh`:
```bash
  AR      drivers/irqchip/built-in.a
../scripts/Makefile.build:45: ../drivers/ksu/Makefile: No such file or directory
make[3]: *** No rule to make target '../drivers/ksu/Makefile'.  Stop.
make[2]: *** [../scripts/Makefile.build:642: drivers/ksu] Error 2
make[1]: *** [/home/runner/work/ksu_rm_k30su/ksu_rm_k30su/Realking_kernel_sm8250/Makefile:1266: drivers] Error 2
```

compiler： https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240304-release

**Comment by Rohail33** [comment]
> I get a compilation error when I execute `build_kernel.sh`:
> 
> ```shell
>   AR      drivers/irqchip/built-in.a
> ../scripts/Makefile.build:45: ../drivers/ksu/Makefile: No such file or directory
> make[3]: *** No rule to make target '../drivers/ksu/Makefile'.  Stop.
> make[2]: *** [../scripts/Makefile.build:642: drivers/ksu] Error 2
> make[1]: *** [/home/runner/work/ksu_rm_k30su/ksu_rm_k30su/Realking_kernel_sm8250/Makefile:1266: drivers] Error 2
> ```
> 
> compiler： https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240304-release

If you're using main branch then.. after cloning the kernel do "git submodule init && git submodule update" then build the kernel.

**Comment by kongqi404** [comment]
Thanks for the reminder, I forgot about the clone submodule.
