### ISSUE TITLE
小米10s(thyme)可以直接用吗

### ISSUE THREAD

**Issue by acai66** [Rohail33/Realking_kernel_sm8250#15]

**Comment by Rohail33** [comment]
Yes.. it can be used directly, you just need to update the thyme_defconfig, add all the necessary and missing configs. And then compile it only. What you can do is compare the thyme _defconfig with alioth_defconfig ( ignoring the device specific configs ) , add back the missing configs and make sure the device specific configs of thyme are all present

**Comment by acai66** [comment]
> Yes.. it can be used directly, you just need to update the thyme_defconfig, add all the necessary and missing configs. And then compile it only. What you can do is compare the thyme _defconfig with alioth_defconfig ( ignoring the device specific configs ) , add back the missing configs and make sure the device specific configs of thyme are all present

Thanks.
