### ISSUE TITLE
Light Sensor and Magnetic Sensor Not Working on ColorOS 14 (OnePlus 8T)

### ISSUE THREAD

**Issue by toraidl** [Rohail33/Realking_kernel_sm8250#18]
Hey there!

First off, thanks a bunch for your appreciation for the work on the OnePlus 8 series! 😊

👋 I've been digging into the open-source code, and I hit a bit of a roadblock. It seems like after successfully compiling and starting the code, the light sensor and magnetic sensor decided to take a coffee break and aren't registering at all.

Here's what I found in the logs:
logcat: 
**05-09 07:34:50.504  1818  2616 W HidlServiceManagement: Waited one second for android.hardware.sensors@2.0::ISensors/default
05-09 07:34:50.504   712   712 I hwservicemanager: Since android.hardware.sensors@2.0::ISensors/default is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting).
05-09 07:34:50.505  1818  2616 I HidlServiceManagement: getService: Trying again for android.hardware.sensors@2.0::ISensors/default...
05-09 07:34:50.506   712  3023 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.sensors@2.0::ISensors/default": error code: 0x20**

dmesg: 

**[   13.469238] (6)[2142:oplus_sensor_fb]<sensor_feedback>adsp_value = 2, node_type=0
[   13.469343] (2)[101:sensor_feedback]<sensor_feedback>event_id =1000, count =0
[   13.469348] (2)[101:sensor_feedback]<sensor_feedback>sensor_list virt_sns = 0x98, phy_sns = 0x58
[   13.469351] (2)[101:sensor_feedback]<sensor_feedback>event_id =1, count =1
[   13.469356] (2)[101:sensor_feedback]<sensor_feedback>payload1 =NULL$$EventField@@device_ps_init_fail$$FieldData@@2$$detailData@@0 0 0$$SensorName@@0x0
[   13.469452] (2)[101:sensor_feedback]<sensor_feedback>send oplus kevent fb
[   18.366445] (4)[1:init]init: Control message: Could not find 'android.frameworks.sensorservice@1.0::ISensorManager/default' for ctl.interface_start from pid: 712 (/system/bin/hwservicemanager)
[   18.698840] (4)[1:init]init: Control message: Could not find 'android.hardware.sensors@2.0::ISensors/default' for ctl.interface_start from pid: 712 (/system/bin/hwservicemanager)**

Got any tricks up your sleeve or pointers on where to look next? I'm all ears (and sensors) for any advice you might have. Thanks a bunch! 🙏

PS: I have comipled the stock source code https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250/tree/oneplus/sm8250_u_14.0.0_op8t , got the same issue.
[dmesg.log](https://github.com/Rohail33/Realking_kernel_sm8250/files/15257045/dmesg.log)

**Comment by Rohail33** [comment]
> Hey there!
> 
> First off, thanks a bunch for your appreciation for the work on the OnePlus 8 series! 😊
> 
> 👋 I've been digging into the open-source code, and I hit a bit of a roadblock. It seems like after successfully compiling and starting the code, the light sensor and magnetic sensor decided to take a coffee break and aren't registering at all.
> 
> Here's what I found in the logs: logcat: **05-09 07:34:50.504 1818 2616 W HidlServiceManagement: Waited one second for android.hardware.sensors@2.0::ISensors/default 05-09 07:34:50.504 712 712 I hwservicemanager: Since android.hardware.sensors@2.0::ISensors/default is not registered, trying to start it as a lazy HAL (if it's not configured to be a lazy HAL, it may be stuck starting or still starting). 05-09 07:34:50.505 1818 2616 I HidlServiceManagement: getService: Trying again for android.hardware.sensors@2.0::ISensors/default... 05-09 07:34:50.506 712 3023 W libc : Unable to set property "ctl.interface_start" to "android.hardware.sensors@2.0::ISensors/default": error code: 0x20**
> 
> dmesg:
> 
> **[ 13.469238] (6)[2142:oplus_sensor_fb]<sensor_feedback>adsp_value = 2, node_type=0 [ 13.469343] (2)[101:sensor_feedback]<sensor_feedback>event_id =1000, count =0 [ 13.469348] (2)[101:sensor_feedback]<sensor_feedback>sensor_list virt_sns = 0x98, phy_sns = 0x58 [ 13.469351] (2)[101:sensor_feedback]<sensor_feedback>event_id =1, count =1 [ 13.469356] (2)[101:sensor_feedback]<sensor_feedback>payload1 =NULL$$EventField@@device_ps_init_fail$$FieldData@@2$$detailData@@0 0 0$$SensorName@@0x0 [ 13.469452] (2)[101:sensor_feedback]<sensor_feedback>send oplus kevent fb [ 18.366445] (4)[1:init]init: Control message: Could not find 'android.frameworks.sensorservice@1.0::ISensorManager/default' for ctl.interface_start from pid: 712 (/system/bin/hwservicemanager) [ 18.698840] (4)[1:init]init: Control message: Could not find 'android.hardware.sensors@2.0::ISensors/default' for ctl.interface_start from pid: 712 (/system/bin/hwservicemanager)**
> 
> Got any tricks up your sleeve or pointers on where to look next? I'm all ears (and sensors) for any advice you might have. Thanks a bunch! 🙏
> 
> PS: I have comipled the stock source code https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250/tree/oneplus/sm8250_u_14.0.0_op8t , got the same issue. [dmesg.log](https://github.com/Rohail33/Realking_kernel_sm8250/files/15257045/dmesg.log)

Hey there... It seems we've already hit a dead end.. i myself have been looking onto this issue... But couldn't found any solution.. it seems OnePlus hasn't pushed all the changes fot the latest Firmwares that's why it's happening... What can be done is reverse engineering on the stock kernel maybe.. or something like that to get the missing changes we need.  ( Ps: the sensors work on below 587 firmwares )
Another solution which could be retrofitting sensor changes from newer op phones.

**Comment by toraidl** [comment]
Hi， 
Thank you for your reply. 
I thought it can't be fixed , but  I just found this commit: 
https://github.com/ppajda/android_kernel_oneplus_sm8250/commit/6ba92032d051dab0aabb98adfa0f2529484cd023
it works!!

**Comment by Rohail33** [comment]
> Hi， Thank you for your reply. I thought it can't be fixed , but I just found this commit: [ppajda/android_kernel_oneplus_sm8250@6ba9203](https://github.com/ppajda/android_kernel_oneplus_sm8250/commit/6ba92032d051dab0aabb98adfa0f2529484cd023) it works!!

Ah does all the sensors work fine after this commit?

**Comment by toraidl** [comment]
yep, I tried it on KB2000_14.0.0.500(CN01) and
just upgrade to  KB2000_14.0.0.600(CN01)  
All works.

**Comment by Rohail33** [comment]
> yep, I tried it on KB2000_14.0.0.500(CN01) and just upgrade to KB2000_14.0.0.600(CN01) All works.

Ok thanks for showing me this commit. Solved a freaking issue for me.
