### ISSUE TITLE
Allows modification of battery charging capacity and battery charging design capacity

### ISSUE THREAD

**Issue by Misakei** [Rohail33/Realking_kernel_sm8250#24]
Device: alioth
System: miui13 13.0.10.0 android 12
Kernel version: 16.2 16.4 16.6.16.8 17.0

I'm using a third-party battery(rated capacity: 5600mah, typical capacity: 5750mah), and I can't change it to the specified value using the command.
echo 5500000 > /sys/class/power_supply/bms/charge_full
echo 5500000 > /sys/class/power_supply/bms/charge_full_design

I wish the capacity limit could be liberalized to allow a battery capacity of at least 6000mah (value 60000000)
🙏🙏🙏

**Comment by Rohail33** [comment]
> Device: alioth System: miui13 13.0.10.0 android 12 Kernel version: 16.2 16.4 16.6.16.8 17.0
> 
> I'm using a third-party battery(rated capacity: 5600mah, typical capacity: 5750mah), and I can't change it to the specified value using the command. echo 5500000 > /sys/class/power_supply/bms/charge_full echo 5500000 > /sys/class/power_supply/bms/charge_full_design
> 
> I wish the capacity limit could be liberalized to allow a battery capacity of at least 6000mah (value 60000000) 🙏🙏🙏

hey there,
Regarding your question, it's not possible to "increase" the battery detection through kernel. as it is dependent upon battery profile to detect maximum value of the battery ( and they should be existent, E.g We added the apollo's orignal battery support in alioth too.) and 3rd party batteries does not have profiles which are existent to kernels. hence we can't do anything about them, rest assure that your battery won't overcharge or get damage because the drivers already predicts and estimates the health of your battery.

**Comment by Misakei** [comment]
> hey there, Regarding your question, it's not possible to "increase" the battery detection through kernel. as it is dependent upon battery profile to detect maximum value of the battery ( and they should be existent, E.g We added the apollo's orignal battery support in alioth too.) and 3rd party batteries does not have profiles which are existent to kernels. hence we can't do anything about them, rest assure that your battery won't overcharge or get damage because the drivers already predicts and estimates the health of your battery.

你好,
![Screenshot_2024-09-26-10-27-12-507_com miui cit](https://github.com/user-attachments/assets/a69cec40-3e55-42e3-80bc-cc2d8aa735b3)
虽然我使用的是第三方电池,但是电池在CIT中被识别为alioth原有的电池配置文件.如图


![IMG_20240926_103317](https://github.com/user-attachments/assets/09988b08-6ad3-4915-8445-7aaee858ddfe)
正因为第三方电池被识别为alioth原有电池,
电池有5500mah容量,但是只能充满到4513mah.
我所希望的就是允许修改alioth原有电池配置文件的容量,
这个需求不止我一个人需要,大量的alioth(k40)用户,原有电池使用2-3年以上,容量衰减到不足一半,很多人更换了容量更大的电池(5000-6000mah),
Realking_kernel支持修改充满容量,这将是一个非常好的特性.😊

**Comment by Misakei** [comment]
顺便说一下,当前内核charge_full可以修改为小于4513000的任意数值,大于4513000的数值无法修改.😊

**Comment by Rohail33** [comment]
> > hey there, Regarding your question, it's not possible to "increase" the battery detection through kernel. as it is dependent upon battery profile to detect maximum value of the battery ( and they should be existent, E.g We added the apollo's orignal battery support in alioth too.) and 3rd party batteries does not have profiles which are existent to kernels. hence we can't do anything about them, rest assure that your battery won't overcharge or get damage because the drivers already predicts and estimates the health of your battery.
> 
> Hello, although I am using a third-party battery, the battery is recognized as alioth's original battery profile in CIT. As shown in the figure ![Screenshot_2024-09-26-10-27-12-507_com miui cit](https://private-user-images.githubusercontent.com/33886929/370964672-a69cec40-3e55-42e3-80bc-cc2d8aa735b3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDU3NTMsIm5iZiI6MTcyNzM0NTQ1MywicGF0aCI6Ii8zMzg4NjkyOS8zNzA5NjQ2NzItYTY5Y2VjNDAtM2U1NS00MmUzLTgwYmMtY2MyZDhhYTczNWIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEwMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmOTgzMTcwNTRjY2RmMjViMzI2YjhkMjUzZmY0MjFiMzdjNTQ2YmEzNjU0YTRlM2VjN2U4OTZlOWY0YTI2YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qAd0gyMkxL-5HX_l3QijDaES82UkuVJjyQuC8cDdJY8)
> 
> ![IMG_20240926_103317](https://private-user-images.githubusercontent.com/33886929/370965136-09988b08-6ad3-4915-8445-7aaee858ddfe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDU3NTMsIm5iZiI6MTcyNzM0NTQ1MywicGF0aCI6Ii8zMzg4NjkyOS8zNzA5NjUxMzYtMDk5ODhiMDgtNmFkMy00OTE1LTg0NDUtN2FhZWU4NThkZGZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEwMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4N2EzYTRlMjVkYTBlMWNiNWVlZjMyNjFmYjkxODMwZmVmYTM1MTgyMTUwMTRmMzdhOGZhN2E2ZmNlMTM1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J1jY3gG1Ofy-OckeTShEp7hFYCj9K5b0CzTOfjkcoGQ) Because the third-party battery is identified as the original battery of alioth, the battery has a capacity of 5500mah, but it can only be fully charged to 4513mah. What I hope is to allow the capacity of the original battery configuration file of alioth to be modified. This demand is not only for me. A large number of alioth (k40) users have used the original battery for more than 2-3 years, and the capacity has decayed to less than half. Many people have replaced the battery with a larger capacity (5000-6000mah). Realking_kernel supports modifying the full capacity, which will be a very good feature. 😊

Altho the battery is being recognized as orignal Battery but it's still not the original battery of alioth. And as i said it's not possible to increase the maximum value of battery detection since it's dependent on battery profiles. And these 3rd party does not have a known battery profile which can be found inside any kernel. That's what limiting us. And for that the profile needs be present in the base Linux kernel. Until that's not done we as kernel devs can't do anything about it.

**Comment by Misakei** [comment]
Altho the battery is being recognized as orignal Battery but it's still not the original battery of alioth. And as i said it's not possible to increase the maximum value of battery detection since it's dependent on battery profiles. And these 3rd party does not have a known battery profile which can be found inside any kernel. That's what limiting us. And for that the profile needs be present in the base Linux kernel. Until that's not done we as kernel devs can't do anything about it.

我这里有一个内核(仅适用于alioth),可以修改charge_full_design&charge_full到任意数值,如果有帮助到你们开发的话,请你们拿来参考.
[Voyager-KSU-ALIOTH-10863b99-miui-ab.zip](https://github.com/user-attachments/files/17148041/Voyager-KSU-ALIOTH-10863b99-miui-ab.zip)

**Comment by Rohail33** [comment]
> Altho the battery is being recognized as orignal Battery but it's still not the original battery of alioth. And as i said it's not possible to increase the maximum value of battery detection since it's dependent on battery profiles. And these 3rd party does not have a known battery profile which can be found inside any kernel. That's what limiting us. And for that the profile needs be present in the base Linux kernel. Until that's not done we as kernel devs can't do anything about it.
> 
> I have a kernel here (only for alioth), which can modify charge_full_design & charge_full to any value. If it helps you develop, please use it as a reference. [Voyager-KSU-ALIOTH-10863b99-miui-ab.zip](https://github.com/user-attachments/files/17148041/Voyager-KSU-ALIOTH-10863b99-miui-ab.zip)

Pm me on telegram: @Rohail33 
We'll discuss it there more. For now iam closing this
