### ISSUE TITLE
Attempt to support Apatch

### ISSUE THREAD

**Issue by TYOPXN360** [Rohail33/Realking_kernel_sm8250#31]
At present, it seems that realking does not support Apatch. Trying to add config that supports Apatch and compile the kernel, and then using Apatch patches, will cause the system to get stuck in the MI interface
In my opinion, I need to use Apache as my root manager because Apache has kernel module functionality

**Comment by Rohail33** [comment]
> At present, it seems that realking does not support Apatch. Trying to add config that supports Apatch and compile the kernel, and then using Apatch patches, will cause the system to get stuck in the MI interface In my opinion, I need to use Apache as my root manager because Apache has kernel module functionality

That's because realking has KernelSu baked into the tree.. Remove that, and then add Apatch then you should be fine.

**Comment by TYOPXN360** [comment]
> That's because realking has KernelSu baked into the tree.. Remove that, and then add Apatch then you should be fine.

I have already set config_ksu=n in the config, so theoretically there should be no kernelsu involved

**Comment by Rohail33** [comment]
> > That's because realking has KernelSu baked into the tree.. Remove that, and then add Apatch then you should be fine.
> 
> I have already set config_ksu=n in the config, so theoretically there should be no kernelsu involved

That's true. But still I'll suggest removing it completely. And then checking. Some members from my group already tried patching the kernel and it worked for them.

**Comment by TYOPXN360** [comment]
> That's true. But still I'll suggest removing it completely. And then checking. Some members from my group already tried patching the kernel and it worked for them.

How to completely remove kernelsu? When I git clone the kernel tree to the local, I found that the kernelsu folder was empty, so I just added config_ksu=n and reconfigured to KALLSYMS=y and reconfigured to KALLSYMS-ALL=y in the configs, and then started compiling
Flashing boot after being patched by Apatch can cause the system to get stuck in the MI interface
The device is Apollo, and the system is lineage22.1

**Comment by Rohail33** [comment]
> > That's true. But still I'll suggest removing it completely. And then checking. Some members from my group already tried patching the kernel and it worked for them.
> 
> How to completely remove kernelsu? When I git clone the kernel tree to the local, I found that the kernelsu folder was empty, so I just added config_ksu=n and reconfigured to KALLSYMS=y and reconfigured to KALLSYMS-ALL=y in the configs, and then started compiling Flashing boot after being patched by Apatch can cause the system to get stuck in the MI interface The device is Apollo, and the system is lineage22.1

I think the issue is with enabling the kallsyms config that and krpobes were broken after upstreaming afaik(altho i think you don't need kallsyms since it's just for debugging purposes) do check the official documentary or other kernels (non gki ones ofc) in how they added apatch. But do check on that. Try manually patching the kernel. And after cloning do Git submodule init , git submodule update. Then remove the ksu hooks, check the history of fs and drivers/input and you'll find them. Remove all the commits and also check the history of gitsubmodule. Then patch the kernel manually with apatch and you should be fine.

**Comment by TYOPXN360** [comment]
> I think the issue is with enabling the kallsyms config that and krpobes were broken after upstreaming afaik(altho i think you don't need kallsyms since it's just for debugging purposes) do check the official documentary or other kernels (non gki ones ofc) in how they added apatch. But do check on that. Try manually patching the kernel. And after cloning do Git submodule init , git submodule update. Then remove the ksu hooks, check the history of fs and drivers/input and you'll find them. Remove all the commits and also check the history of gitsubmodule. Then patch the kernel manually with apatch and you should be fine.

Perhaps you can make a branch that completely removes kernelsu, as kernelsu's support for non GKI has stopped, and apatch may be a good choice. I am not very familiar with certain operations. Currently, I only know how to simply add config to the kernel. However, I am trying my best to solve the problem. If the kernel source tree can directly support apatch without any modifications, that would be great
By the way, if you don't add KALLSYMS-ALL=y, the kernel won't be able to patch apatch
