### ISSUE TITLE
compile this project for miui

### ISSUE THREAD

**Issue by yycmd** [Rohail33/Realking_kernel_sm8250#6]
What editing environment do I need if I want to compile this project for miui

**Comment by Rohail33** [comment]
> What editing environment do I need if I want to compile this project for miui

Well you just need to use Ubuntu ( most preferred ) , and install a few packages listed below :
openssh-server screen git openjdk-8-jdk android-tools-adb bc bison \
build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev \
lib32readline-dev lib32z1-dev  liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev \
libtinfo5 libncurses5
These all should do good for compilation.

**Comment by yycmd** [comment]
> 



> > What editing environment do I need if I want to compile this project for miui
> 
> Well you just need to use Ubuntu ( most preferred ) , and install a few packages listed below : openssh-server screen git openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev libtinfo5 libncurses5 These all should do good for compilation.

Well you just need to use Ubuntu ( most preferred ) , and install a few packages listed below :
openssh-server screen git openjdk-8-jdk android-tools-adb bc bison
build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev
lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev
libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev
libtinfo5 libncurses5
These all should do good for compilation.

> > What editing environment do I need if I want to compile this project for miui
> 
> Well you just need to use Ubuntu ( most preferred ) , and install a few packages listed below : openssh-server screen git openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev libtinfo5 libncurses5 These all should do good for compilation.

Which cross-compile chain to use?

**Comment by yycmd** [comment]
> > What editing environment do I need if I want to compile this project for miui
> 
> Well you just need to use Ubuntu ( most preferred ) , and install a few packages listed below : openssh-server screen git openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev libtinfo5 libncurses5 These all should do good for compilation.

Which cross-compile chain to use?

**Comment by Rohail33** [comment]
> > > What editing environment do I need if I want to compile this project for miui
> > 
> > 
> > Well you just need to use Ubuntu ( most preferred ) , and install a few packages listed below : openssh-server screen git openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev libtinfo5 libncurses5 These all should do good for compilation.
> 
> Which cross-compile chain to use?

you can use zyc-clang 17 ( which is most preferred )

**Comment by yycmd** [comment]
> > > > What editing environment do I need if I want to compile this project for miui
> > > 
> > > 
> > > Well you just need to use Ubuntu ( most preferred ) , and install a few packages listed below : openssh-server screen git openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev libtinfo5 libncurses5 These all should do good for compilation.
> > 
> > 
> > Which cross-compile chain to use?
> 
> you can use zyc-clang 17 ( which is most preferred )

thanks very much
