### ISSUE TITLE
make O=out munch_defconfig - error

### ISSUE THREAD

**Issue by novice161** [Rohail33/Realking_kernel_sm8250#7]
make[1]: Entering directory '/root/Realking_kernel_sm8250/out'
python2: can't open file '../scripts/gcc-wrapper.py': [Errno 2] No such file or directory

**Comment by Rohail33** [comment]
> make[1]: Entering directory '/root/Realking_kernel_sm8250/out' python2: can't open file '../scripts/gcc-wrapper.py': [Errno 2] No such file or directory

This is an issue within your build environment, there is an work around to solve this but it's an temporary solution, go to init/kconfig and delete confit cc_version and it's content. And then build, proper fix should be fixing your building environment.
